Setup CI (#1)

diff --git a/test/integration b/test/integration
--- a/test/integration
+++ b/test/integration
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
 set -euo pipefail
+set -x
 
 GIT_MONOREPO_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
 
@@ -13,9 +14,22 @@ cleanup() {
    rm -rf "$TEST_PATH" || true
 }
 
+git-monorepo() {
+   "${GIT_MONOREPO_PATH}/git-monorepo" "$@"
+}
+
 fail() {
    echoerr "test failed: $*"
    exit 1
+}
+
+setup_git_if_necessary() {
+   local -r email="$(git config --get user.email)"
+   if [ -n "$email" ]; then
+      return 0 
+   fi
+   git config --global user.email "bot@github.com"
+   git config --global user.name "GitHub bot"
 }
 
 setup_monorepo() {
@@ -30,7 +44,7 @@ setup_monorepo() {
 
 setup_microrepos() {
    cd "${GITHUB}/mono"
-   for i in 1 2; do git monorepo extract proj${i} "$GITHUB"/proj${i}; done
+   for i in 1 2; do git-monorepo extract proj${i} "$GITHUB"/proj${i}; done
 }
 
 clone_proj1() {
@@ -55,7 +69,7 @@ push_proj1() {
 
 update_mono() {
    cd "$GITHUB"/mono
-   git monorepo pull newfeature
+   git-monorepo pull newfeature
 }
 
 merge_mono() {
@@ -64,7 +78,7 @@ merge_mono() {
 }
 
 update_proj1() {
-   git monorepo push
+   git-monorepo push
 }
 
 pull_proj1() {
@@ -73,35 +87,25 @@ pull_proj1() {
    git pull
 }
 
-check_proj1() {
-   cd "$LOCAL"/proj1
+check_repo() {
+   local -r path="$1"
+   local -r file="$2"
+
+   cd "$path"
 
    local x
    x="$(git rev-parse --abbrev-ref HEAD)"
-   [ "$x" == "master" ] || fail proj1 "wrong branch" "$x"
+   [ "$x" == "master" ] || fail "$path" "wrong branch" "$x"
 
    x="$(git log)"
-   echo "$x" | grep -q 'proj1/newfeature' || fail proj1 "commit not found" "$x"
+   echo "$x" | grep -q 'proj1/newfeature' || fail "$path" "commit not found" "$x"
 
-   x="$(cat ./file1.js)"
-   echo "$x" | grep -q 'newchange' || fail proj1 "newchange not found" "$x"
-}
-
-check_mono() {
-   cd "$GITHUB"/mono
-
-   local x
-   x="$(git rev-parse --abbrev-ref HEAD)"
-   [ "$x" == "master" ] || fail mono "wrong branch" "$x"
-
-   x="$(git log)"
-   echo "$x" | grep -q 'proj1/newfeature' || fail mono "commit not found" "$x"
-
-   x="$(cat ./proj1/file1.js)"
-   echo "$x" | grep -q 'newchange' || fail mono "newchange not found" "$x"
+   x="$(cat "$file")"
+   echo "$x" | grep -q 'newchange' || fail "$path" "newchange not found" "$x"
 }
 
 main() {
+   setup_git_if_necessary
    setup_monorepo
    setup_microrepos
    clone_proj1
@@ -112,8 +116,9 @@ main() {
    update_proj1
    pull_proj1
 
-   check_proj1
-   check_mono
+   check_repo "$GITHUB"/mono ./proj1/file1.js
+   check_repo "$GITHUB"/proj1 ./file1.js
+   check_repo "$LOCAL"/proj1 ./file1.js
 }
 
 trap cleanup INT TERM EXIT
